---

# ExaBGP + ExaCheck Docker Container

services:

  exacheck:
    image: exacheck/exacheck:latest
    container_name: exacheck
    restart: unless-stopped

    # If you want to use the host network, uncomment the following line
    # This may be a shortcut for IPv6 support
    #network_mode: host

    volumes:
      # Either the configuration files or a volume/folder containing the configuration files
      # exabgp.conf and exacheck.yaml must be mounted for the container to work.
      - ./exabgp.conf:/etc/exabgp/exabgp.conf:ro
      - ./exacheck.yaml:/etc/exabgp/exacheck.yaml:ro

    # The following environment variables can be set to change the container settings if required.
    #environment:
      # Set to change time zone in container
      #- TZ=UTC
      # To allow inbound BGP connections, uncomment the following line
      #- exabgp.tcp.bind=0.0.0.0

    ports:
      - 179:179/tcp
